sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "node"
install:
  - npm install
before_script:
  - npx gulp clean && npx gulp lint && npx gulp build
