sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - "node"
install:
  - npm install
before_script:
  - npx gulp clean
  - npx gulp lint
  - npx gulp build
